# Generated by Django 4.2.3 on 2023-07-10 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INSNAME', models.CharField(max_length=250)),
                ('FULLMARKS', models.IntegerField()),
                ('PASSMARKS', models.IntegerField()),
                ('FILENAME', models.FileField(default=None, max_length=250, null=True, upload_to='WordFiles')),
                ('ADDTEXT', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
