# Generated by Django 4.2.3 on 2023-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stinfomodels',
            name='Touched_Status',
            field=models.BooleanField(default=False),
        ),
    ]
